### ISSUE TITLE
RetryTxSender / Unused txRetryTimeoutMs 

### ISSUE THREAD

**Issue by ricardojmendez** [drift-labs/keeper-bots-v2#113]
The global config has a property called `txRetryTimeoutMs`.  

https://github.com/drift-labs/keeper-bots-v2/blob/6e4e84f94dab0efc8ad73af3314f81322ccd0086/src/config.ts#L121

The latest merge to mainnet-beta (commit 79b5fca) includes an optional `RetryTxSender`, with a fixed timeout. 

https://github.com/drift-labs/keeper-bots-v2/blob/6e4e84f94dab0efc8ad73af3314f81322ccd0086/src/index.ts#L278
                        
`txRetryTimeoutMs` doesn't seem to be used anywhere.

Was that property meant for the `RetryTxSender`?

**Comment by wphan** [comment]
> Looks like this was fixed in [a7d71fa](https://github.com/drift-labs/keeper-bots-v2/commit/a7d71faa51d423e051318054e96bec14071f2c53)
> 
> cc @wphan

yeah this was fixed, thanks for the ping
