### ISSUE TITLE
Has an account on Drift to be created first? How then to specify it in a config yaml file?

### ISSUE THREAD

**Issue by tabatinga0xffff** [drift-labs/keeper-bots-v2#141]
When I was signing up by my Phantom wallet at the website, a warning was given, along the lines of "you must have 0.2 SOL in your wallet in order to be able to create or activate an account"

Has an account on Drift to be created **first**? How? 

How then will I specify my account in a yaml-config file?

**Comment by wphan** [comment]
> When I was signing up by my Phantom wallet at the website, a warning was given, along the lines of "you must have 0.2 SOL in your wallet in order to be able to create or activate an account"
That's the rent required to create a new account, it will be reclaimed if you ever delete your account.

> Has an account on Drift to be created first? How?
Yes, either through the UI, or start using this repo: `yarn run dev --init-user`, the same rent applies. make sure to remove the flag to run the bot

> How then will I specify my account in a yaml-config file?
set `global.keeperPrivateKey` in the config file, or the `KEEPER_PRIVATE_KEY` environment variable. This needs to be the private key of the account or a file to the private key

**Comment by tabatinga0xffff** [comment]
Thanks
