### ISSUE TITLE
filler last active slot != current slot

### ISSUE THREAD

**Issue by ricardojmendez** [drift-labs/keeper-bots-v2#62]
Hi folks,

I've been getting this error from the filler bot: `filler last active slot (XXX) != current slot (YYY)`, where XXX can be 26k slots behind Y. Not entirely clear what it means nor how to address it. It seems to happen only when filling orders, and triggers work fine.

I suspect this might not be a program but RPC-related, however the fact that some instructions do work leaves me wondering.

Any pointers?

**Comment by 0xbigz** [comment]
26k slots seems really high

**Comment by ricardojmendez** [comment]
Here's one I just got:

```
SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 2: custom program error: 0x185f
    at Connection._callee89$ (/Users/Sources/drift/keeper-bots-v2/node_modules/@solana/web3.js/src/connection.ts:5922:13)
    at tryCatch (/Users/Sources/drift/keeper-bots-v2/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (/Users/Sources/drift/keeper-bots-v2/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:133:17)
    at Generator.next (/Users/Sources/drift/keeper-bots-v2/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (/Users/Sources/drift/keeper-bots-v2/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/Sources/drift/keeper-bots-v2/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  logs: [
    'Program ComputeBudget111111111111111111111111111111 invoke [1]',
    'Program ComputeBudget111111111111111111111111111111 success',
    'Program dRiftyHA39MWEi3m9aunc5MzRF1JYuBsbn6VPcn33UH invoke [1]',
    'Program log: Instruction: FillPerpOrder',
    'Program log: Order does not exist 18670283',
    'Program dRiftyHA39MWEi3m9aunc5MzRF1JYuBsbn6VPcn33UH consumed 13320 of 1400000 compute units',
    'Program dRiftyHA39MWEi3m9aunc5MzRF1JYuBsbn6VPcn33UH success',
    'Program dRiftyHA39MWEi3m9aunc5MzRF1JYuBsbn6VPcn33UH invoke [1]',
    'Program log: Instruction: RevertFill',
    'Program log: Error RevertFill thrown at programs/drift/src/instructions/keeper.rs:122',
    'Program log: filler last active slot (214112014) != current slot (214166813)',
    'Program log: AnchorError occurred. Error Code: RevertFill. Error Number: 6239. Error Message: RevertFill.',
    'Program dRiftyHA39MWEi3m9aunc5MzRF1JYuBsbn6VPcn33UH consumed 12122 of 1386680 compute units',
    'Program dRiftyHA39MWEi3m9aunc5MzRF1JYuBsbn6VPcn33UH failed: custom program error: 0x185f'
  ]
}
```

You can see in this case it's even further behind - about 55k slots.

**Comment by ricardojmendez** [comment]
Two more cases, after restarting the filler:

```
'Program log: filler last active slot (214112014) != current slot (214172622)',
```

and 

```
'Program log: filler last active slot (214112014) != current slot (214174316)',
```

Notice the last active slot is the same on all. I'm not familiar enough with the filler yet to have mapped out when it gets updated.

**Comment by 0xbigz** [comment]
oh I think thats just the revert logic. Basically checks if you hit the fill and otherwise fails if you were too late.

**Comment by ricardojmendez** [comment]
Thanks. So is this just an "outcompeted" scenario?

I'm curious... why doesn't the _filler last active slot_ change? There were hours between some of those error messages.

**Comment by wphan** [comment]
> Thanks. So is this just an "outcompeted" scenario?
> 
> I'm curious... why doesn't the _filler last active slot_ change? There were hours between some of those error messages.

the filler's `last_active_slot` is updated to the current slot on a successful fill. The difference between the two become so large because that's essentially the last time the filler had a successful fill (or the last time that account was 'active', i.e. placed an order).

**Comment by ricardojmendez** [comment]
Perfect, thanks to you both. I'll leave the issue open for now, document it on a PR after I'm done with #58, and then submit a documentation update to close it.
