### ISSUE TITLE
Bug (?): Unused MAX_POSITION_EXPOSURE on floatingMaker

### ISSUE THREAD

**Issue by ricardojmendez** [drift-labs/keeper-bots-v2#65]
The example `floatingMaker` bot is supposed to use MAX_POSITION_EXPOSURE, declared here:

https://github.com/drift-labs/keeper-bots-v2/blob/1c20aa58bdc24faf97a213d342cadf52bf0e1996/src/bots/floatingMaker.ts#L88

It gets mentioned on the comment for updateAgentState:

https://github.com/drift-labs/keeper-bots-v2/blob/1c20aa58bdc24faf97a213d342cadf52bf0e1996/src/bots/floatingMaker.ts#L217

However, it never gets used in the code.

**Comment by wphan** [comment]
this was probably left over from when it was copied over from another project. `floatingMaker.ts` was really meant as an example for how to post and update floating limit orders, not really meant to be a self contained market maker

**Comment by ricardojmendez** [comment]
Gotcha, thanks! I agree, it seems incomplete, but it's been a good way to cut my teeth on the API while getting familiar with things.
