### ISSUE TITLE
Fillerlite potential error: Bot stops after reaching error

### ISSUE THREAD

**Issue by johnnybtrader** [drift-labs/keeper-bots-v2#73]
I get an error that makes the bot stop.

/src/bots/filler.ts:135:2

const takerNode = node.node;
                        ^
TypeError: Cannot read properties of undefined (reading 'node')

Let me know if you need any more information :)

**Comment by wphan** [comment]
Were you testing on the latest master branch? i think this was fixed yesterday

**Comment by johnnybtrader** [comment]
I didn't realize there was an update. Was able to pull the latest update and have it running now. Thanks!
