### ISSUE TITLE
Another issue not allowing fillerlite bot to run

### ISSUE THREAD

**Issue by johnnybtrader** [drift-labs/keeper-bots-v2#76]
keeper-bots-v2/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/bots/uncrossArbBot.ts:211:51 - error TS2339: Property 'arbPerp' does not exist on type 'JitProxyClient'.

211        const txResult = await this.jitProxyClient.arbPerp({

**Comment by 0xbigz** [comment]
can you try running `yarn`. see there have been updates recently.

**Comment by 0xbigz** [comment]
confirmed that was the issue^

always run `yarn` after pulling new code :)
