### ISSUE TITLE
TypeError on Filler bots

### ISSUE THREAD

**Issue by johnnybtrader** [drift-labs/keeper-bots-v2#79]
Hey, I am still getting the type error on both filler and filler lite bots after pulling the updates with git pull and making sure I ran yarn.

src/utils.ts:129
	if (!node.node.userAccount) {
           ^
TypeError: Cannot read properties of undefined (reading 'node')

**Comment by wphan** [comment]
i believe this was fixed at some point, please reopen if you see it again
